### ISSUE TITLE
关于 v23.32 版本 "自定义" 按钮位置异常的临时过渡方法

### ISSUE THREAD

**Issue by sAMs126** [langren1353/GM_script#114]
自定义图标错位可在自定义样式中临时增加以下代码

```css
/**自定义图标居中*/
div #u{
    display: flex;
}
div #myuser{
    align-self: center;
}
```

效果：
[![NWm7Uf.md.png](https://s1.ax1x.com/2020/06/29/NWm7Uf.md.png)](https://imgchr.com/i/NWm7Uf)

---

其实还有一个小问题，下滑滚动时顶部搜索栏的样式是空了一部分，如下

[![NWmIbt.md.png](https://s1.ax1x.com/2020/06/29/NWmIbt.md.png)](https://imgchr.com/i/NWmIbt)

我个人又添加了一点样式让底部背景补全了：

```css
/**下滑滚动时搜索栏高度*/
.wrapper_new #head.fix-head .s_form {
    height: 70px
}
```

效果：
[![NWmTVP.md.png](https://s1.ax1x.com/2020/06/29/NWmTVP.md.png)](https://imgchr.com/i/NWmTVP)

相关 is: #112 #113

---

写在最后：

- 感谢作者 @langren1353 提供这么优秀的插件
- 以上方法均是在作者修正之前的临时过渡方案，很有可能随着 bai度 页面修改而失效，望悉知
