### ISSUE TITLE
屏幕 1366 x 768 下搜索页 css 设定宽度多余的问题

### ISSUE THREAD

**Issue by fz6m** [langren1353/GM_script#142]
### 问题
目前我的屏幕是 1366 x 768 的，设定了 **边栏开启 + 单列显示** 。

可以看到右边栏太宽导致左边搜索结果栏被挤到下面去了：

![](https://raw.githubusercontent.com/fz6m/Private-picgo/moe/img/20200822013725.png)

![](https://raw.githubusercontent.com/fz6m/Private-picgo/moe/img/20200822014849.png)

### 建议
问题主要在于左边给 `#content_left` 上了一个 80% 的宽度，右边也没适配宽度。

```css
body #container.sam_newgrid #content_left {
    width: 80%;
}
```

经过自定义 css 设定为 auto 宽度好了：

```css
body #container.sam_newgrid #content_left {
    width: auto !important;
}
```

但是我并不清楚在宽屏机上 auto （也就是不设定宽度）会有什么表现，如果有问题，建议做 1440px 以下宽度的 css 适配。
