### ISSUE TITLE
希望能提供选项关闭这个按钮

### ISSUE THREAD

**Issue by spphinslove** [langren1353/GM_script#178]
![图片](https://user-images.githubusercontent.com/11383988/99961472-77695400-2dc9-11eb-9022-2191dd81e7b2.png)

**Comment by langren1353** [comment]
附加10，末尾增加自定义样式表：
```css
body #u #myuser {
    display: none;
}
```
别忘了开启功能10，如果不喜欢背景色及其他调整，可以清空后再填入这部分内容即可
