### ISSUE TITLE
谷歌双列变为了类似一个一个的小框, 而不是平铺

### ISSUE THREAD

**Issue by liukch** [langren1353/GM_script#184]
原来双列到N列都是平铺开的
现在变成了一个一个的小框, 东西都显示不全
如图
![image](https://user-images.githubusercontent.com/35715689/101429925-f40a3f80-393e-11eb-8b5d-c3a6e2de78fb.png)

浏览器是 Chrome

**Comment by liukch** [comment]
设置 如图
![image](https://user-images.githubusercontent.com/35715689/101430008-29169200-393f-11eb-9135-17a76e3c7802.png)

**Comment by liukch** [comment]
又试了一下  百度是正常的  
![image](https://user-images.githubusercontent.com/35715689/101430342-bfe34e80-393f-11eb-8c66-5578422a3de1.png)

**Comment by CoolView** [comment]
可以添加自定义样式
```css
#cnt #center_col, .mw #center_col {
    margin-left: 0;
}
#cnt #center_col {
     width: fit-content;
}
```
