### ISSUE TITLE
谷歌双列显示不居中, 显示不全。

### ISSUE THREAD

**Issue by liukch** [langren1353/GM_script#197]
如图
![image](https://user-images.githubusercontent.com/35715689/103280180-b4e58080-4a0a-11eb-89e3-059251236357.png)

但是换到某些关键词的时候却是好的, 如图:
![image](https://user-images.githubusercontent.com/35715689/103280210-caf34100-4a0a-11eb-9c2c-4390aeef9938.png)

**Comment by liukch** [comment]
发现问题了, 是我之前加的自定义样式的原因

``` css
#cnt #center_col, .mw #center_col {
    margin-left: 0;
}
#cnt #center_col {
     width: fit-content;
}
```
