### ISSUE TITLE
4k屏，150%缩放，浏览器最大化时百度条目偏右，部分内容超出屏幕

### ISSUE THREAD

**Issue by Mrneet** [langren1353/GM_script#230]
如图中圈的部分，很明显不居中，下方还有一个滚动条，右上方的设置和个人登录也到外面去了。但是调整浏览器窗口大小，小于某个宽度之后就居中了，其他显示都变正常了。
![image](https://user-images.githubusercontent.com/30075289/111265549-3771f980-8664-11eb-9d70-b54f8a64ad02.png)

**Comment by astinx** [comment]
我美化了一下, 在自定义样式里面追加入如下样式, 就可以解决了, 还美化了一下, 我2K屏幕, 应该是一样的

```css
/*****百度自定义开始*****/
#wrapper #content_left .result, #wrapper #content_left .c-container{
    border-radius: 35px;
    box-shadow: 0 0px 15px rgba(0,0,0,.15);
    padding: 2%;
    
    width: unset !important;
    max-width: 100%;
    margin-left: 5px;
    margin-right: 15px;
}
#container.sam_newgrid {
    padding-left: 0!important;
    margin-left: 0!important;
}

body #container.sam_newgrid #content_left{
    margin-left: 2vw;
    width: 96vw!important;
}
#wrapper #container.sam_newgrid #content_left{
	padding-left: 0;
}

.new_head_nums_cont_outer{
    text-align: center;
}

@media screen and (min-width:1921px){
    #wrapper_wrapper{
        margin-left:0!important;
    }
    #container.sam_newgrid {
        padding-left: 0!important;
    }
    #head .head_wrapper{transform:translate3d(-120px,0,1px);}
}

.wrapper_new #form .bdsug-new{
    text-align: center;
    width: 66%;
    padding-right: 0;
}
#kw{
    text-align:center;
    font-size:18px;
    font-weight:600;
}

.wrapper_new #form .bdsug-new ul li{
    width:100%;
}

/*****百度自定义end*****/

/*****Google自定义开始*****/
.gLFyf{
    margin-top: -42px!important;
    text-align: center;
    font-size: 20px!important;
    font-weight: 600!important;
}
#main #cnt, #cnt #center_col, #cnt #foot{
    width: 96vw;
}
#rso .g, .vk_c{
    border-radius:35px;
    box-shadow: 0 0px 15px rgba(0,0,0,.15);
	padding: 20px;
}
.sbct{
    text-align: center;
}
/*****Google自定义end*****/
```
