### ISSUE TITLE
谷歌设置双列之后搜索栏内容位置错乱

### ISSUE THREAD

**Issue by Direct-A** [langren1353/GM_script#242]
![image](https://user-images.githubusercontent.com/46991254/114565856-428c6980-9ca4-11eb-9101-41520a4f5f3d.png)

margin-top修改之后位置就正确了

![image](https://user-images.githubusercontent.com/46991254/114566152-95662100-9ca4-11eb-8fd3-acfafae76cd7.png)

**Comment by mqliutie** [comment]
哈哈, 同样遇到这个问题

**Comment by astinx** [comment]
我美化了一下, 在自定义样式里面追加入如下样式, 就可以解决了, 还美化了一下

```css
/*****百度自定义开始*****/
#wrapper #content_left .result, #wrapper #content_left .c-container{
    border-radius: 35px;
    box-shadow: 0 0px 15px rgba(0,0,0,.15);
    padding: 2%;
    
    width: unset !important;
    max-width: 100%;
    margin-left: 5px;
    margin-right: 15px;
}
#container.sam_newgrid {
    padding-left: 0!important;
    margin-left: 0!important;
}

body #container.sam_newgrid #content_left{
    margin-left: 2vw;
    width: 96vw!important;
}
#wrapper #container.sam_newgrid #content_left{
	padding-left: 0;
}

.new_head_nums_cont_outer{
    text-align: center;
}

@media screen and (min-width:1921px){
    #wrapper_wrapper{
        margin-left:0!important;
    }
    #container.sam_newgrid {
        padding-left: 0!important;
    }
    #head .head_wrapper{transform:translate3d(-120px,0,1px);}
}

.wrapper_new #form .bdsug-new{
    text-align: center;
    width: 66%;
    padding-right: 0;
}
#kw{
    text-align:center;
    font-size:18px;
    font-weight:600;
}

.wrapper_new #form .bdsug-new ul li{
    width:100%;
}

/*****百度自定义end*****/

/*****Google自定义开始*****/
.gLFyf{
    margin-top: -42px!important;
    text-align: center;
    font-size: 20px!important;
    font-weight: 600!important;
}
#main #cnt, #cnt #center_col, #cnt #foot{
    width: 96vw;
}
#rso .g, .vk_c{
    border-radius:35px;
    box-shadow: 0 0px 15px rgba(0,0,0,.15);
	padding: 20px;
}
.sbct{
    text-align: center;
}
/*****Google自定义end*****/
```
