### ISSUE TITLE
谷歌搜索显示结果界面，搜索文字在搜索框下面

### ISSUE THREAD

**Issue by Holdasecond** [langren1353/GM_script#243]
谷歌搜索显示结果界面，搜索文字在搜索框下面，不知道是别的插件干扰影响还是脚本本身问题。百度没有此问题，在谷歌初始搜索界面也不会出现。
![Snipaste_2021-04-14_11-21-05](https://user-images.githubusercontent.com/52282922/114649753-b0bc4500-9d13-11eb-9f69-7f6b3a5aa541.png)

**Comment by YadominJinta** [comment]
好像是因为新加了一个 按 '/' 跳转到搜索框的功能的原因

**Comment by Abandon339** [comment]
+1

**Comment by likeqc** [comment]
+1

**Comment by astinx** [comment]
我美化了一下, 在自定义样式里面追加入如下样式, 就可以解决了, 还美化了一下


```css

/*****百度自定义开始*****/
#wrapper #content_left .result, #wrapper #content_left .c-container{
    border-radius: 35px;
    box-shadow: 0 0px 15px rgba(0,0,0,.15);
    padding: 2%;
    
    width: unset !important;
    max-width: 100%;
    margin-left: 5px;
    margin-right: 15px;
}
#container.sam_newgrid {
    padding-left: 0!important;
    margin-left: 0!important;
}

body #container.sam_newgrid #content_left{
    margin-left: 2vw;
    width: 96vw!important;
}
#wrapper #container.sam_newgrid #content_left{
	padding-left: 0;
}

.new_head_nums_cont_outer{
    text-align: center;
}

@media screen and (min-width:1921px){
    #wrapper_wrapper{
        margin-left:0!important;
    }
    #container.sam_newgrid {
        padding-left: 0!important;
    }
    #head .head_wrapper{transform:translate3d(-120px,0,1px);}
}

.wrapper_new #form .bdsug-new{
    text-align: center;
    width: 66%;
    padding-right: 0;
}
#kw{
    text-align:center;
    font-size:18px;
    font-weight:600;
}

.wrapper_new #form .bdsug-new ul li{
    width:100%;
}

/*****百度自定义end*****/

/*****Google自定义开始*****/
.gLFyf{
    margin-top: -42px!important;
    text-align: center;
    font-size: 20px;
    font-weight: 600;
}
#main #cnt, #cnt #center_col, #cnt #foot{
    width: 96vw;
}
#rso .g, .vk_c{
    border-radius:35px;
    box-shadow: 0 0px 15px rgba(0,0,0,.15);
	padding: 20px;
}
/*****Google自定义end*****/
```

**Comment by wlvx** [comment]
> 我美化了一下, 在自定义样式里面追加入如下样式, 就可以解决了, 还美化了一下
> 
> ```css
> /*****百度自定义开始*****/
> #wrapper #content_left .result, #wrapper #content_left .c-container{
>     border-radius: 35px;
>     box-shadow: 0 0px 15px rgba(0,0,0,.15);
>     padding: 2%;
>     
>     width: unset !important;
>     max-width: 100%;
>     margin-left: 5px;
>     margin-right: 15px;
> }
> #container.sam_newgrid {
>     padding-left: 0!important;
>     margin-left: 0!important;
> }
> 
> body #container.sam_newgrid #content_left{
>     margin-left: 2vw;
>     width: 96vw!important;
> }
> #wrapper #container.sam_newgrid #content_left{
> 	padding-left: 0;
> }
> 
> .new_head_nums_cont_outer{
>     text-align: center;
> }
> 
> @media screen and (min-width:1921px){
>     #wrapper_wrapper{
>         margin-left:0!important;
>     }
>     #container.sam_newgrid {
>         padding-left: 0!important;
>     }
>     #head .head_wrapper{transform:translate3d(-120px,0,1px);}
> }
> 
> .wrapper_new #form .bdsug-new{
>     text-align: center;
>     width: 66%;
>     padding-right: 0;
> }
> #kw{
>     text-align:center;
>     font-size:18px;
>     font-weight:600;
> }
> 
> .wrapper_new #form .bdsug-new ul li{
>     width:100%;
> }
> 
> /*****百度自定义end*****/
> 
> /*****Google自定义开始*****/
> .gLFyf{
>     margin-top: -42px!important;
>     text-align: center;
>     font-size: 20px!important;
>     font-weight: 600!important;
> }
> .minidiv .gLFyf{margin-top:-32px!important}
> #main #cnt, #cnt #center_col, #cnt #foot{
>     width: 96vw;
> }
> #rso .g, .vk_c{
>     border-radius:35px;
>     box-shadow: 0 0px 15px rgba(0,0,0,.15);
> 	padding: 20px;
> }
> .sbct{
>     text-align: center;
> }
> .g{
>     padding: 20px!important;
> }
> /*****Google自定义end*****/
> ```

确实解决了，但是两列的情况下搜索条目铺满整个屏幕，感觉不是那么美观。哈哈哈哈

**Comment by likeqc** [comment]
> 
> 确实解决了，但是两列的情况下搜索条目铺满整个屏幕，感觉不是那么美观。哈哈哈哈

那就只要关键代码，哈哈哈
.gLFyf{
    margin-top: -42px!important;
}

**Comment by mzdluo123** [comment]
我也遇到了这个问题，上面的代码确实可以解决问题，感谢

**Comment by astinx** [comment]
> > 我美化了一下, 在自定义样式里面追加入如下样式, 就可以解决了, 还美化了一下
> > ```css
> > /*****百度自定义开始*****/
> > #wrapper #content_left .result, #wrapper #content_left .c-container{
> >     border-radius: 35px;
> >     box-shadow: 0 0px 15px rgba(0,0,0,.15);
> >     padding: 2%;
> >     
> >     width: unset !important;
> >     max-width: 100%;
> >     margin-left: 5px;
> >     margin-right: 15px;
> > }
> > #container.sam_newgrid {
> >     padding-left: 0!important;
> >     margin-left: 0!important;
> > }
> > 
> > body #container.sam_newgrid #content_left{
> >     margin-left: 2vw;
> >     width: 96vw!important;
> > }
> > #wrapper #container.sam_newgrid #content_left{
> > 	padding-left: 0;
> > }
> > 
> > .new_head_nums_cont_outer{
> >     text-align: center;
> > }
> > 
> > @media screen and (min-width:1921px){
> >     #wrapper_wrapper{
> >         margin-left:0!important;
> >     }
> >     #container.sam_newgrid {
> >         padding-left: 0!important;
> >     }
> >     #head .head_wrapper{transform:translate3d(-120px,0,1px);}
> > }
> > 
> > .wrapper_new #form .bdsug-new{
> >     text-align: center;
> >     width: 66%;
> >     padding-right: 0;
> > }
> > #kw{
> >     text-align:center;
> >     font-size:18px;
> >     font-weight:600;
> > }
> > 
> > .wrapper_new #form .bdsug-new ul li{
> >     width:100%;
> > }
> > 
> > /*****百度自定义end*****/
> > 
> > /*****Google自定义开始*****/
> > .gLFyf{
> >     margin-top: -42px!important;
> >     text-align: center;
> >     font-size: 20px!important;
> >     font-weight: 600!important;
> > }
> > .minidiv .gLFyf{margin-top:-32px!important}
> > #main #cnt, #cnt #center_col, #cnt #foot{
> >     width: 96vw;
> > }
> > #rso .g, .vk_c{
> >     border-radius:35px;
> >     box-shadow: 0 0px 15px rgba(0,0,0,.15);
> > 	padding: 20px;
> > }
> > .sbct{
> >     text-align: center;
> > }
> > .g{
> >     padding: 20px!important;
> > }
> > /*****Google自定义end*****/
> > ```
> 
> 确实解决了，但是两列的情况下搜索条目铺满整个屏幕，感觉不是那么美观。哈哈哈哈

这个是我的习惯来的, 你如果不想满屏幕, 就将上面96vw改一下就好了, 你可以改80, 不过你的边距宽度又要改了, 因为作者原本的样式设计是有点问题的.

**Comment by astinx** [comment]
> > 确实解决了，但是两列的情况下搜索条目铺满整个屏幕，感觉不是那么美观。哈哈哈哈
> 
> 那就只要关键代码，哈哈哈
> .gLFyf{
> margin-top: -42px!important;
> }

这个还会引申一个问题, 在下拉时候, 顶部那个浮动的搜索框的字还是会偏移, 还要把
> .minidiv .gLFyf{margin-top:-32px!important}

这句话加上

**Comment by likeqc** [comment]
> 
> 这个还会引申一个问题, 在下拉时候, 顶部那个浮动的搜索框的字还是会偏移, 还要把
> 
> > .minidiv .gLFyf{margin-top:-32px!important}
> 
> 这句话加上

大佬就是大佬，刚刚正准备说这个问题呢，这下子总算完美了

**Comment by wlvx** [comment]
> > > 我美化了一下, 在自定义样式里面追加入如下样式, 就可以解决了, 还美化了一下
> > > ```css
> > > /*****百度自定义开始*****/
> > > #wrapper #content_left .result, #wrapper #content_left .c-container{
> > >     border-radius: 35px;
> > >     box-shadow: 0 0px 15px rgba(0,0,0,.15);
> > >     padding: 2%;
> > >     
> > >     width: unset !important;
> > >     max-width: 100%;
> > >     margin-left: 5px;
> > >     margin-right: 15px;
> > > }
> > > #container.sam_newgrid {
> > >     padding-left: 0!important;
> > >     margin-left: 0!important;
> > > }
> > > 
> > > body #container.sam_newgrid #content_left{
> > >     margin-left: 2vw;
> > >     width: 96vw!important;
> > > }
> > > #wrapper #container.sam_newgrid #content_left{
> > > 	padding-left: 0;
> > > }
> > > 
> > > .new_head_nums_cont_outer{
> > >     text-align: center;
> > > }
> > > 
> > > @media screen and (min-width:1921px){
> > >     #wrapper_wrapper{
> > >         margin-left:0!important;
> > >     }
> > >     #container.sam_newgrid {
> > >         padding-left: 0!important;
> > >     }
> > >     #head .head_wrapper{transform:translate3d(-120px,0,1px);}
> > > }
> > > 
> > > .wrapper_new #form .bdsug-new{
> > >     text-align: center;
> > >     width: 66%;
> > >     padding-right: 0;
> > > }
> > > #kw{
> > >     text-align:center;
> > >     font-size:18px;
> > >     font-weight:600;
> > > }
> > > 
> > > .wrapper_new #form .bdsug-new ul li{
> > >     width:100%;
> > > }
> > > 
> > > /*****百度自定义end*****/
> > > 
> > > /*****Google自定义开始*****/
> > > .gLFyf{
> > >     margin-top: -42px!important;
> > >     text-align: center;
> > >     font-size: 20px!important;
> > >     font-weight: 600!important;
> > > }
> > > .minidiv .gLFyf{margin-top:-32px!important}
> > > #main #cnt, #cnt #center_col, #cnt #foot{
> > >     width: 96vw;
> > > }
> > > #rso .g, .vk_c{
> > >     border-radius:35px;
> > >     box-shadow: 0 0px 15px rgba(0,0,0,.15);
> > > 	padding: 20px;
> > > }
> > > .sbct{
> > >     text-align: center;
> > > }
> > > .g{
> > >     padding: 20px!important;
> > > }
> > > /*****Google自定义end*****/
> > > ```
> > 
> > 
> > 确实解决了，但是两列的情况下搜索条目铺满整个屏幕，感觉不是那么美观。哈哈哈哈
> 
> 这个是我的习惯来的, 你如果不想满屏幕, 就将上面96vw改一下就好了, 你可以改80, 不过你的边距宽度又要改了, 因为作者原本的样式设计是有点问题的.

非常感谢！

**Comment by astinx** [comment]
> > 这个还会引申一个问题, 在下拉时候, 顶部那个浮动的搜索框的字还是会偏移, 还要把
> > > .minidiv .gLFyf{margin-top:-32px!important}
> > 
> > 
> > 这句话加上
> 
> 大佬就是大佬，刚刚正准备说这个问题呢，这下子总算完美了

并不完美, 如果多列情况下, 如果有图片那种结果出来,会有一块一块的, 
我加了2句在Google那, 或者你复制我上面的, 我修改过
```css
#rso{grid-template-columns:none;grid-template-areas:none;}
#rso>.ULSxyf:not(.g){grid-template-columns:none;grid-template-areas:unset;grid-column-gap:unset;}
```
