### ISSUE TITLE
我美化了一下, 在自定义样式里面追加入如下样式, 就可以解决了, 还美化了一下

### ISSUE THREAD

**Issue by Direct-A** [langren1353/GM_script#245]
我美化了一下, 在自定义样式里面追加入如下样式, 就可以解决了, 还美化了一下

```css
/*****百度自定义开始*****/
#wrapper #content_left .result, #wrapper #content_left .c-container{
    border-radius: 35px;
    box-shadow: 0 0px 15px rgba(0,0,0,.15);
    padding: 2%;
    
    width: unset !important;
    max-width: 100%;
    margin-left: 5px;
    margin-right: 15px;
}
#container.sam_newgrid {padding-left: 0!important;margin-left: 0!important;}

body #container.sam_newgrid #content_left{margin-left: 2vw;width: 96vw!important;}
#wrapper #container.sam_newgrid #content_left{padding-left: 0;}
.new_head_nums_cont_outer{text-align: center;}

@media screen and (min-width:1921px){
    #wrapper_wrapper{margin-left:0!important;}
    #container.sam_newgrid {padding-left: 0!important;}
    #head .head_wrapper{transform:translate3d(-120px,0,1px);}
}

.wrapper_new #form .bdsug-new{
    text-align: center;
    width: calc(100% - 114px);
    padding-right: 0;
}
#kw{text-align:center;font-size:18px;font-weight:600;}

.wrapper_new #form .bdsug-new ul li{width:100%;}
/*****百度自定义end*****/

/*****Google自定义开始*****/
.gLFyf{
    margin-top: -42px!important;
    text-align: center;
    font-size: 20px!important;
    font-weight: 600!important;
}
.minidiv .gLFyf{margin-top:-32px!important}
#main #cnt, #cnt #center_col, #cnt #foot{width:96vw;}
#rso .g, .vk_c{
    border-radius:35px;
    box-shadow: 0 0px 15px rgba(0,0,0,.15);
    padding: 20px;
}
.sbct{text-align: center;}
#rcnt #res h3, #rcnt #extrares h3{font-size:20px;}
.MUFPAc{margin-left:0!important;font-size:1.1rem;}
.WE0UJf{margin-left: 0!important;}
.LHJvCe{
    display: block!important;
    text-align: center!important;
    width: 100%;
}
.g{padding:20px!important;}
#rso{grid-template-columns:none;grid-template-areas:none;}
#rso>.ULSxyf:not(.g){grid-template-columns:none;grid-template-areas:unset;grid-column-gap:unset;}
/*****Google自定义end*****/
```

_Originally posted by @astinx in https://github.com/langren1353/GM_script/issues/243#issuecomment-819241382_
