### ISSUE TITLE
谷歌视频栏宽宽宽出天际爆出屏幕

### ISSUE THREAD

**Issue by XSeanU** [langren1353/GM_script#437]
如图所示。

![image](https://user-images.githubusercontent.com/51028862/153756365-163ebede-9987-4e37-a303-d6f262907396.png)

只有单列居中/多列模式不会出现这个bug，而在原始排列/单列/关闭自定义都会出现。

![image](https://user-images.githubusercontent.com/51028862/153756436-97d3d85d-0d1b-42b6-a1bc-2ff567fb4871.png)

**Comment by anlondon** [comment]
我也遇到了，不过我知道怎么解决

**Comment by anlondon** [comment]
我也遇到了，不过我知道怎么解决

##### 解决 （二选一）
1. 关闭自动加载
2. 在附加10中，添加以下内容即可解决
```
.g {
 line-height:1.58;
 text-align:left;
 position: relative;
}
```
![图片](https://user-images.githubusercontent.com/34559111/154923511-89c9b9a2-42a8-4d66-9d5f-5f38350e4514.png)

##### 原因：
是因为每个视频元素都有一个`position:absolute`的css,目的是，页面加载时将视频绝对定位到某处，因为是自动加载页面，导致绝对定位错误。

加入上述代码后，虽然不再会撑得整个页面，不过视频内容显示会有些问题。

**Comment by BahuangShanren** [comment]
> 只有单列居中/多列模式不会出现这个bug

@yiyangthesame `单列居中`时，实际上也会出现，无论`附加10-自定义样式`是默认，还是清空，又或是 @anlondon 提供的方法，都是这个[效果](https://www.google.com/search?q=minecraft+background+music)：

<img src="https://user-images.githubusercontent.com/48022216/158024508-d19c5479-264e-4aef-b446-840ef42c0146.png">

<img src="https://user-images.githubusercontent.com/48022216/158024364-d5a98cbe-e216-4e90-ad6e-2dafd4d0422d.png" width="50%">

> 在附加10中，添加以下内容即可解决

@anlondon 我多次尝试过你的方法，仍未成功，请问你可以将的完整CSS发出来吗？

**Comment by anlondon** [comment]
> > 只有单列居中/多列模式不会出现这个bug
> 
> @yiyangthesame `单列居中`时，在不同的搜索内容及其返回结果中，这种情况实际上也会出现。
> 
> 比如搜索`minecraft background music`时，无论`附加10-自定义样式`是默认、清空、或是 @anlondon 提供的CSS，都是这个[效果](https://www.google.com/search?q=minecraft+background+music)：
> 
> ![](https://user-images.githubusercontent.com/48022216/158024508-d19c5479-264e-4aef-b446-840ef42c0146.png)
> 
> <img alt="" width="50%" src="https://user-images.githubusercontent.com/48022216/158024364-d5a98cbe-e216-4e90-ad6e-2dafd4d0422d.png">
> 
> > 在附加10中，添加以下内容即可解决
> 
> @anlondon 我多次尝试过你的方法，仍未成功，请问你可以将完整的CSS发出来吗？

我才发现我的问题和你们的不太一样😂
```css
.g {
 line-height:1.58;
 text-align:left;
 position: relative;
 width:600px;
}
.U1TUId{
  float: left;
  position: relative;
  height:82px;
}
```
我简单看了下，你或许可以在 `.g{}`中加入` width:600px;`来解决

完整css:
```css
/**计数器的颜色样式*/
div .AC-CounterT{
  background: #FD9999;
}
/**右侧栏的样式-其实不开启更好看一些*/
#content_right{
  padding: 20px 15px 15px;
  border-radius: 5px;
  background-color: #fff;
  box-sizing: border-box;
  box-shadow: 0 0 20px 2px rgba(0, 0, 0, .1);
  -webkit-box-shadow: 0 0 20px 2px rgba(0, 0, 0, .1);
  -moz-box-shadow: 0 0 20px 2px rgba(0, 0, 0, .1);
}
body[baidu] {
  position: relative;
}
body[baidu]:before {
  position: fixed;
  width: 100%;
  height: 100%;
  top: 0;
  left: 0;
  content: '';
  background-image: url('https://img.tujidu.com/image/5fdde8468423e.jpg');
  background-size: 100% auto;
  opacity: 1; /*背景图透明度=0.8，最大1*/
}
/**隐藏首页的大图标-修复可能导致外援样式异常**/
body[baidu] #s_lg_img_new{
  display:none !important;
}
body[baidu] .c-container{
  border-radius: 5px;
  background-color: rgba(255,255,255, 0.3) !important; /*百度搜索块体的颜色；透明度=0.1，最大1*/
}
body[baidu] .c-container h3{
  background-color: rgba(248,248,248, 0.3) !important; /*百度搜索块体 - 标题的颜色；透明度=0.1，最大1*/
}
.g {
 line-height:1.58;
 text-align:left;
 position: relative;
 width:600px;
}
.U1TUId{
  float: left;
  position: relative;
  height:82px;
}
```
我的设置：
![图片](https://user-images.githubusercontent.com/34559111/158499081-f8730f1d-a892-47e9-a452-d983322d7003.png)

@BahuangShanren

**Comment by anlondon** [comment]
我现在**真正遇到了题主的问题**，

**解决**
勾选附加10，并写入以下css代码即可解决 **视频列表过宽**的问题
```css
/*视频过宽*/
g-scrolling-carousel{
    display:inline-grid !important;
}
.Lu0opc.ESkzqb.pQXcHc,
.Lu0opc.ESkzqb.pQXcHc:hover {
 opacity:1 !important;
 visibility:inherit !important;
}
```
@yiyangthesame
