### ISSUE TITLE
google单列居中样式增加

### ISSUE THREAD

**Issue by CHminggao** [langren1353/GM_script#483]
``` css
#main #cnt{
	width:100% !important;
}

#main .MUFPAc{
	margin-left:auto !important;
}

#main #appbar,slim_appbar{
	margin: 0 auto !important;
}

#main #appbar .LHJvCe{
	width: 100% !important;
	justify-content: center !important;
}

#main #tn_1 .LkcePc{
	width: auto !important;
}

#main #hdtbMenus{
	display: grid !important;
    justify-content: center !important;
}

```

效果：
![动画](https://user-images.githubusercontent.com/28477604/165485263-15a4a6f2-e901-42d3-9ea8-1deea53c9989.gif)

**Comment by CHminggao** [comment]
增加一个，用于单列居中时右侧卡片
``` css
#main #rhs{
    position: absolute !important;
    right: 10px !important;
}
```
![image](https://user-images.githubusercontent.com/28477604/165489798-fdad6601-e6e9-4882-9e28-5dc9c8c1a1cf.png)
