### ISSUE TITLE
谷歌护眼模式单列居中时样式问题

### ISSUE THREAD

**Issue by xnng** [langren1353/GM_script#49]
![image](https://user-images.githubusercontent.com/38936252/64902558-d4ed1580-d6db-11e9-8853-666bd5039137.png)

谷歌搜索开启单列居中护眼模式时右边会多出一个元素块

暂时只能通过附加自定义样式来解决：

```css
#rhs {
   display: none !important;
}
```
