### ISSUE TITLE
google界面黑暗模式不匹配

### ISSUE THREAD

**Issue by Michaelzhouisnotwhite** [langren1353/GM_script#501]

**Comment by ccsugar** [comment]
same

**Comment by yangchuansheng** [comment]
同样的问题，不过我添加了自定义的 css 解决了，作者可以参考一下：

```css
@-moz-document domain("www.google.com") {

/**计数器的颜色样式*/
div .AC-CounterT{
  background: #5574b3;
}
  
  &:before {
    position: fixed;
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
    content: '';
    background-size: 100% auto;
  }
  
  .LGOjhe {
    background-color: #2c303c !important; 
  }
  
  #rso .g, .k8XOCe {
    background-color: #2c303c !important; 
  }
  
  #rso .g:hover {
    background-color: #2c303c !important; 
  }
  
  .sfbg{
    margin-top: -10px;
  }
  
  .yg51vc{
    background-color: transparent !important; 
  }
  
  #rcnt #res h3, #rcnt #extrares h3 {
    color: white !important;
  }

}
```

![](https://pek3b.qingstor.com/kubesphere-community/images/202206191036917.png)
