### ISSUE TITLE
一个什么都实现了一点的CSS（百度）

### ISSUE THREAD

**Issue by QhtIsNotAvailable** [langren1353/GM_script#576]
推荐配置：stylus（插件）->百度多栏卡片搜索 + 东方永页机（脚本）+ AC百度（原始样式，百度Lite）
主要功能：去除百度工具栏，个人头像和“大家还在搜”，添加背景图和各种半透明，磨砂和阴影效果，把百度的logo变成了摆烂=-=
理想效果图：![CSS_百度搜索 - 个人 - Microsoft​ Edge 2022_11_25 16_32_23.png](https://s2.loli.net/2022/11/25/gb6zjnkRTpCL2PY.png)
CSS代码：
```CSS
/*1.背景图*/
body[baidu] {
    position: relative;
    background-image: url("https://s2.loli.net/2022/11/24/FNrI2kqm6754lKM.png");
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
}

/*2.头部框*/
/*2.1.头部磨砂*/
#head{
    backdrop-filter:blur(10px);
}

/*2.2.搜索框透明度*/
.head_wrapper .bg.s_ipt_wr.new-pmd.quickdelete-wrap {
    opacity: 0.75;
}

/*2.3.字体设置*/
.head_wrapper #kw {
    font-size:18px;
    font-family:思源黑体 CN regular;
}

/*2.4.下拉框匹配*/
.head_wrapper .bdsug.bdsug-new.bdsugbg{
    margin-top:12px;
    width:558px !important;
    opacity:0.75;
    overflow:hidden;
    /*background-color:transparent;*/
}

/*2.5.隐藏用户头像*/
.head_wrapper #user{
    display:none !important;
}

/*2.6.摆烂！(更改百度LOGO)*/
#result_logo{
    margin-top:20px !important;
    opacity:0.7 !important;
    length:120px;
    background-image:url("https://s2.loli.net/2022/11/25/sbFpKzjHX2WEPRr.png")!important;
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: contain;
}

/*2.7.隐藏设置(OFF)*/
/*
.head_wrapper .pf {
    display: none !important;
}
*/

/*3.头部框下栏*/
/*3.1.搜索顶部占位*/
.result-molecule.new-pmd[tpl="app/head-tab"]{
    height:35px;
    /*忽略[tpl="app/head-tab"]直接修改height会导致翻页错误,这是因为result-molecule指向不止一个元素*/
}

/*3.2.隐藏搜索设置和工具栏*/
#wrapper .options_2Vntk,#s_tab{
    display:none;
}

/*4.搜索主体*/
/*4.1.隐藏“大家还在搜”*/
.result-op.c-container.new-pmd[tpl="recommend_list"]{
    display:none !important;
}

/*4.2.搜索块体*/
#content_left>.c-container {
    border-radius: 0 !important;
    background-color: rgba(222, 241, 239, 0.5) !important;
    -webkit-box-shadow: 3px 3px 10px 7px rgba(0,0,0,0.5) !important;
    -moz-box-shadow: 3px 3px 10px 7px rgba(0,0,0,0.5) !important;
    box-shadow: 3px 3px 10px 7px rgba(0,0,0,0.5) !important;
}

/*4.3.搜索块体-标题(OFF)*/
/*#content_left>.c-container h3 {
    background-color: rgba(255, 255, 255, 1) !important;
}
*/

/*4.4.取消滚动条(未实现)*/
/*滚动条取消后无法滚动页面，不知道能否使用CSS语言解决该问题
    2713120e09145c370e122f152809122710070f0a07040a03464612030a5c57555353545052565f5f54
    Xor with a fixed Hex digit.
    如果您做出了此功能，欢迎使用上述方式联系我：）
*/
```
