### ISSUE TITLE
分享自用样式修改--兼容搜索引擎快捷跳转

### ISSUE THREAD

**Issue by 3biubiu** [langren1353/GM_script#592]
```
 div[role="complementary"] {
    display: none !important;
}
#sej-container {
  margin-right: auto;
  width: fit-content;
  margin-left: auto;
}
.MUFPAc {
  margin-left : 0px
}
.appbar {
    margin: 0 auto;
    /* width: fit-content; */
}
.minidiv .logo {
  top : 0px;
}
#rso .g, .vk_c {
  border-radius: 10px;
  width : 600px !important;
}
#rso .g:hover {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.1), 0 6px 20px 0 rgba(0, 0, 0, 0.1);
     transition: all 0.15s ease;
     
} 
```
优化了谷歌搜索的部分样式和布局错乱问题,移除了谷歌摘要,优化自动下一页 内容靠左的问题 适配搜索引擎快捷跳转 居中展示
![image](https://user-images.githubusercontent.com/63720467/217728114-1aa0ec3a-14d3-4625-9d61-6087c7ca8a99.png)

**Comment by ConnorTomato** [comment]
大佬，这个去除“精选摘要”，是否现在失效呢？

**Comment by 3biubiu** [comment]
> 大佬，这个去除“精选摘要”，是否现在失效呢？

应该没失效 但是自动展开下一页之后的样式好像出问题了 你可以试试

**Comment by ConnorTomato** [comment]
` div[role="complementary"] {
    display: none !important;
}` 
去除“精选摘要”，在我这里没生效，怎么排查啊？我的操做是全部直接丢进那个附加10 CSS 框里

**Comment by 3biubiu** [comment]
> ` div[role="complementary"] { display: none !important; }` 去除“精选摘要”，在我这里没生效，怎么排查啊？我的操做是全部直接丢进那个附加10 CSS 框里

我看了一下是生效的,你是不是没有勾选应用css

**Comment by 3biubiu** [comment]
> ![image](https://user-images.githubusercontent.com/57027969/229732013-8c95ed18-fd20-477a-a6b2-704f1bcd5d06.png) 还有得救吗？

```css

div[role="complementary"] {
    display: none !important;
}

#sej-container {
    margin-right: auto;
    width: fit-content;
    margin-left: auto;
}

.MUFPAc {
    margin-left: 0px
}

.appbar {
    margin: 0 auto;
    /* width: fit-content; */
}

.minidiv .logo {
    top: 0px;
}

#rso .g,
.vk_c {
    border-radius: 10px;
    width: 698px !important;
}

#rso .g:hover {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.1), 0 6px 20px 0 rgba(0, 0, 0, 0.1);
    transition: all 0.15s ease;

}

#rcnt {
    display: flex;
    flex-direction: column-reverse;
}

.chat-gpt,
.GyAeWb .chat-gpt-container.sidebar-free {
    margin-left: 0px;
    max-width: 698px
}

.gpt-promotion-link {
    display: none;
}

#chat-gpt-for-google-search-enhance {
    width: 698px;
    margin-left: 0px !important;
}

.search-enhance {
    width: 698px;
}

.aaa26a714 .chat-gpt .chat-gpt-card {
    width: 698px;
}

.chat-gpt {
    width: 698px;
}
.UUbT9 {
  width: 719px !important;
}
.yG4QQe {
   display: none !important;
}

```

**Comment by ConnorTomato** [comment]
有效，已解决问题，感谢。

**Comment by Nyte-BK201** [comment]
同样的问题。用了楼主的css
```
div[role="complementary"] {
    display: none !important;
}

.MUFPAc {
    margin-left: 0px
}

#rcnt {
    display: flex;
    flex-direction: column-reverse;
}

.search-enhance {
    width: 698px;
}
```
页面上方的显示是正常的，但是精选摘要会被挪到页面最下方。只要划到这个位置，自动翻页就会出错。正常情况加载下一页后，新的页面会在当前位置向下拓展。在有精选摘要的搜索结果中，翻页会无法拓展。请问如何屏蔽精选摘要？
![image](https://github.com/langren1353/GM_script/assets/32067657/1a023487-ffc3-42b6-aade-3ad642f8188f)

**Comment by 3biubiu** [comment]
> 同样的问题。用了楼主的css
> 
> ```
> div[role="complementary"] {
>     display: none !important;
> }
> 
> .MUFPAc {
>     margin-left: 0px
> }
> 
> #rcnt {
>     display: flex;
>     flex-direction: column-reverse;
> }
> 
> .search-enhance {
>     width: 698px;
> }
> ```
> 
> 页面上方的显示是正常的，但是精选摘要会被挪到页面最下方。只要划到这个位置，自动翻页就会出错。正常情况加载下一页后，新的页面会在当前位置向下拓展。在有精选摘要的搜索结果中，翻页会无法拓展。请问如何屏蔽精选摘要？ ![image](https://user-images.githubusercontent.com/32067657/240946948-1a023487-ffc3-42b6-aade-3ad642f8188f.png)

我目前没有发现很好的方法 主要是在css选择器方面没有找到什么规律,总是有遗漏的
```css
div[role="complementary"] {
    display: none !important;
}

#sej-container {
    margin-right: auto;
    width: fit-content;
    margin-left: auto;
}

.MUFPAc {
    margin-left: 0px
}

.appbar {
    margin: 0 auto;
    /* width: fit-content; */
}

.minidiv .logo {
    top: 0px;
}

#rso .g,
.vk_c {
    border-radius: 10px;
    width: 698px !important;
}

#rso .g:hover {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.1), 0 6px 20px 0 rgba(0, 0, 0, 0.1);
    transition: all 0.15s ease;

}

#rcnt {
    display: flex;
    flex-direction: column-reverse;
}

.search-enhance {
    width: 698px;
}

.aaa26a714 .chat-gpt .chat-gpt-card {
    width: 698px;
}

.chat-gpt {
    width: 698px;
}
.UUbT9 {
  width: 719px !important;
}
.yG4QQe {
   display: none !important;
}
div[data-hveid="CAYQAw"] {
    display: none !important;
}
```
