### ISSUE TITLE
DealRedirect is not a function

### ISSUE THREAD

**Issue by llsccm** [langren1353/GM_script#622]
https://github.com/langren1353/GM_script/blob/10d5e00749e89f8851be231dea1630c890a1b767/AC-Baidu-SoGou-Google-NoRedirect.user.js#L3002

这里使用函数声明会不会更好，函数表达式控制台经常报错

![截图](https://github.com/langren1353/GM_script/assets/48448919/b9383678-489f-4a56-ae4b-7ec49906973a)

百度卡片左边图片设置了浮动，右边区域没浮动导致两个区域有点问题，右边区域开启BFC可以不受到浮动元素的影响

```css
#content_left .new-pmd .c-span9 {
    overflow: hidden;
}
```

**Comment by llsccm** [comment]
@langren1353  26.05版本baiduCommonStyle.less这里的#rs元素我没找着 这个样式没有生效吧

```less
#wrapper #rs {
  padding: unset;
  margin: 20px;
  border-radius: 5px;
  z-index: 1;

  .new-pmd {
    padding: 20px;

    .c-span9 {
      overflow: hidden;
    }
  }

  .tt {
    margin: -20px -20px 5px -20px;
    padding: 15px 20px;
    background-color: #f8f8f8;
    border-radius: 5px 5px 0px 0px;
  }

  table {
    width: 630px;
    padding: 5px 15px;

    tr a {
      margin-top: 5px;
      margin-bottom: 5px;
      color: #3476d2;
    }

    tr a:hover {
      text-decoration: underline;
    }
  }
}
```
