### ISSUE TITLE
[百度配置] 单列居中选项位置偏左

### ISSUE THREAD

**Issue by FinchOrigin** [langren1353/GM_script#721]
问题场景：
![图片](https://github.com/user-attachments/assets/9c38f7ca-934b-4969-95f7-ed1e38ea73db)

原因
```css
body.showRight #wrapper #container.sam_newgrid #content_left {
  transform: translateX(calc(6vw - 251px));
}
```

消掉之后就符合预期了
![图片](https://github.com/user-attachments/assets/b47a3ccb-3fe9-4e92-8b8b-f5ba3fe5a0ff)
